### ISSUE TITLE
Why gulp?

### ISSUE THREAD

**Issue by alastair-todd** [evertonrobertoauler/cli-universal-demo#7]
Thanks for the repo. 

Just wondering why the need for gulp on build, and what exactly is it doing?

**Comment by evertonrobertoauler** [comment]
The @angular/compiler-cli does not transpile scss into css before generating the AOT code, thats why I'm using gulp to transpile scss into css before running ngc and restore the scss content.

**Comment by alastair-todd** [comment]
ng-cli does though are we not reinventing the wheel?

also I've not been able to find any recommended way of developing AU. No
watching code changes?

All examples appear to suggest...

stop server
full prod rebuild
start server

yeaouch!

**Comment by evertonrobertoauler** [comment]
Ok, 

While I'm developing, I'm using `ng serve` in JIT mode, because the @angular/compiler-cli does not have a watch mode parameter yet, I could build a watch task with gulp or use webpack-dev-server to rebuild and restart the server every time something change, but it'll take a lot of machine resources and the developer experience would not be very good.

The renderModuleFactory from @angular/platform-server needs AOT compiled code, and the only way I found to generate the AOT code is using the @angular/compiler-cli command that does not work well with scss files like the @angular/cli does. 

If you find a better way to do the same thing without reinventing the wheel using gulp and webpack, please send me a pull request, I'll be happy to merge it.

**Comment by evertonrobertoauler** [comment]
I'm building a new boilerplate, simpler and litter, using just webpack with AOT by default, in Development and Production mode, try it out, and let me know if it works for you.

https://github.com/evertonrobertoauler/universal-demo
